"""
compter modes from site https://ardupilot.org/copter/docs/parameters.html#fltmode1
"""
MODE_STABILIZE = 0
MODE_ACRO = 1
MODE_ALT_HOLD = 2
MODE_AUTO = 3
MODE_GUIDED = 4
MODE_LOITER = 5
MODE_RTL = 6
MODE_CIRCLE = 7
MODE_LAND = 9
MODE_DRIFT = 11
MODE_SPORT = 13
MODE_FLIP = 14
MODE_AUTO_TUNE = 15
MODE_POS_HOLD = 16
MODE_BRAKE = 17
MODE_THROW = 18
MODE_AVOID_ADSB = 19
MODE_GUIDED_NO_GPS = 20
MODE_SMART_RTL = 21
MODE_FLOW_HOLD = 22
MODE_FOLLOW = 23
MODE_ZIG_ZAG = 24
MODE_SYSTEM_ID = 25
MODE_HELI_AUTOROTATE = 26
MODE_AUTO_RTL = 27